name: Run Selenium Pytest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        suite:
          - tests/test_login1.py
          - tests/test_api.py

    steps:
    - name: Checkout source code from github
      uses: actions/checkout@v4

    - name: Install python 
      uses: actions/setup-python@v5 
      with:
        python-version: '3.13'

    - name: Install necessary libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Chrome libary
      uses: browser-actions/setup-chrome@v1

    - name: Create a test report Folder
      run: mkdir -p report

    - name: Run tests
      #run: pytest -m smoke --html=report/report.html --self-contained-html
      run: |
        pytest ${ { matrix.suite } } --maxfail=1 --disable-warnings -q




    - name: Upload file report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report/report.html
